/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoprog2.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabalhoprog2.controladores.PassageiroController;
import trabalhoprog2.modelos.Passageiro;

/**
 *
 * @author warml
 */
public class FrameConsultaPassageiroVoo extends javax.swing.JFrame {

    /**
     * Creates new form FrameConsultaPassageiroVoo
     */
    public FrameConsultaPassageiroVoo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePassageirosVoo = new javax.swing.JTable();
        jPassageirosVoo = new javax.swing.JLabel();
        jVoo = new javax.swing.JLabel();
        jTextVoo = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();

        jTablePassageirosVoo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Idade", "CPF", "Voo", "Destino", "Classe", "Poltrona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePassageirosVoo);

        jPassageirosVoo.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jPassageirosVoo.setText("Passageiros por Voo");

        jVoo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jVoo.setText("Informe o Voo");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                        .addComponent(jBAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPassageirosVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPassageirosVoo)
                .addGap(26, 26, 26)
                .addComponent(jVoo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar)
                    .addComponent(jBExcluir)
                    .addComponent(jBAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
       String numeroVoo = jTextVoo.getText();
      
      try{ 
       if (!numeroVoo.isEmpty()){
           DefaultTableModel modelo = (DefaultTableModel)jTablePassageirosVoo.getModel();
           modelo.setRowCount(0);
           PassageiroController ctc = new PassageiroController();
            List<Passageiro> passageirosVoo = ctc.consultarPassageiroPorVoo(numeroVoo);
            for (Passageiro passageiro : passageirosVoo){
                modelo.addRow(new String[]{
                    String.valueOf(passageiro.getId()),
                            passageiro.getNome(),
                            String.valueOf(passageiro.getIdade()),
                            passageiro.getCpf(),
                            passageiro.getVoo(),
                            passageiro.getDestino(),
                            passageiro.getClasse(),
                            String.valueOf(passageiro.getPoltrona())
            });
        }
       }
      }  catch (Exception e){
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
    }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            PassageiroController ctc = new PassageiroController();
            int linha = jTablePassageirosVoo.getSelectedRow();
            int id = Integer.parseInt(jTablePassageirosVoo.getValueAt(linha, 0).toString());
            ctc.excluir(id);
            
            DefaultTableModel modelo = (DefaultTableModel)jTablePassageirosVoo.getModel();
            modelo.removeRow(linha);
            JOptionPane.showMessageDialog(rootPane, "Passageiro excluído com sucesso");
            
        }catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um passageiro para excluir");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        try {
            int linha = jTablePassageirosVoo.getSelectedRow();
            int id = Integer.parseInt(jTablePassageirosVoo.getValueAt(linha, 0).toString());
            String nome = jTablePassageirosVoo.getValueAt(linha, 1).toString();
            int idade = Integer.parseInt(jTablePassageirosVoo.getValueAt(linha, 2).toString());
            String cpf = jTablePassageirosVoo.getValueAt(linha, 3).toString();
            String voo = jTablePassageirosVoo.getValueAt(linha, 4).toString();
            String destino = jTablePassageirosVoo.getValueAt(linha, 5).toString();
            String classe = jTablePassageirosVoo.getValueAt(linha, 6).toString();
            int poltrona = Integer.parseInt(jTablePassageirosVoo.getValueAt(linha, 7).toString());
            
            Passageiro passageiro = new Passageiro(nome, idade, cpf, voo, destino, classe, poltrona, id);
            new FrameAtualizarPassageiro(passageiro).setVisible(true);
            this.dispose();
            
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um passageiro para atualizar");
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jPassageirosVoo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePassageirosVoo;
    private javax.swing.JTextField jTextVoo;
    private javax.swing.JLabel jVoo;
    // End of variables declaration//GEN-END:variables
}
