/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoprog2.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabalhoprog2.controladores.AeronaveController;
import trabalhoprog2.modelos.Aeronave;

/**
 *
 * @author warml
 */
public class FrameConsultaAeronave extends javax.swing.JFrame {

    /**
     * Creates new form FrameConsultaAeronave
     */
    public FrameConsultaAeronave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAeronaves = new javax.swing.JTable();
        jAeronaves = new javax.swing.JLabel();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableAeronaves.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Companhia", "Capacidade", "Modelo", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAeronaves);

        jAeronaves.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jAeronaves.setText("Aeronaves");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAtualizar)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jAeronaves, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jAeronaves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel modelo = (DefaultTableModel)jTableAeronaves.getModel();  
        
        AeronaveController ctc = new AeronaveController();
        List<Aeronave> aeronaves = ctc.consultarTodos();
        System.out.println("Aeronaves: " + aeronaves);
        for (Aeronave aeronave : aeronaves){
            modelo.addRow(new String[]{
                String.valueOf(aeronave.getId()),
                         aeronave.getCompanhia(),
                         String.valueOf(aeronave.getCapacidade()),
                         aeronave.getModelo(),
                         String.valueOf(aeronave.getCodigo())
            });
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            AeronaveController ctc = new AeronaveController();
            int linha = jTableAeronaves.getSelectedRow();
            int id = Integer.parseInt(jTableAeronaves.getValueAt(linha, 0).toString());
            ctc.excluir(id);
            
            DefaultTableModel modelo = (DefaultTableModel)jTableAeronaves.getModel();
            modelo.removeRow(linha);
            JOptionPane.showMessageDialog(rootPane, "Aeronave excluída com sucesso");
            
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma aeronave para excluir");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        try {
            int linha = jTableAeronaves.getSelectedRow();
            int id = Integer.parseInt(jTableAeronaves.getValueAt(linha, 0).toString());
            String companhia = jTableAeronaves.getValueAt(linha, 1).toString();
            int capacidade = Integer.parseInt(jTableAeronaves.getValueAt(linha, 2).toString());
            String modelo = jTableAeronaves.getValueAt(linha, 3).toString();
            int codigo = Integer.parseInt(jTableAeronaves.getValueAt(linha, 4).toString());
            
            Aeronave aeronave = new Aeronave(companhia, capacidade, modelo, codigo, id);
            new FrameAtualizarAeronave(aeronave).setVisible(true);
            this.dispose();
            
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma aeronave para atualizar");
        }
            
    }//GEN-LAST:event_jBAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAeronaves;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAeronaves;
    // End of variables declaration//GEN-END:variables
}
