/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoprog2.view;

import javax.swing.JOptionPane;
import trabalhoprog2.controladores.AeronaveController;
import trabalhoprog2.modelos.Aeronave;

/**
 *
 * @author warml
 */
public class FrameAtualizarAeronave extends javax.swing.JFrame {
    private Aeronave aeronave;
    /**
     * Creates new form FrameAtualizarAeronave
     */
    public FrameAtualizarAeronave(Aeronave aeronave) {
        this.aeronave = aeronave;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCompanhia = new javax.swing.JLabel();
        jTextCompanhia = new javax.swing.JTextField();
        jCapacidade = new javax.swing.JLabel();
        jTextCapacidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextModelo = new javax.swing.JTextField();
        jCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jBAtualizar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jCompanhia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCompanhia.setText("Companhia");

        jCapacidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCapacidade.setText("Capacidade");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Modelo");

        jCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCodigo.setText("Código");

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCompanhia)
                    .addComponent(jTextCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCapacidade)
                    .addComponent(jTextCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAtualizar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCompanhia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextCompanhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCapacidade)
                .addGap(18, 18, 18)
                .addComponent(jTextCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCodigo)
                .addGap(18, 18, 18)
                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAtualizar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextCompanhia.setText(aeronave.getCompanhia());
        jTextCapacidade.setText(String.valueOf(aeronave.getCapacidade()));
        jTextModelo.setText(aeronave.getModelo());
        jTextCodigo.setText(String.valueOf(aeronave.getCodigo()));
    }//GEN-LAST:event_formWindowOpened

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        try {
            aeronave.setCompanhia(jTextCompanhia.getText());
            aeronave.setCapacidade(Integer.parseInt(jTextCapacidade.getText()));
            aeronave.setModelo(jTextModelo.getText());
            aeronave.setCodigo(Integer.parseInt(jTextCodigo.getText()));
            
            AeronaveController ctc = new AeronaveController();
            ctc.update(aeronave);
            JOptionPane.showMessageDialog(rootPane, "Aeronave atualizada com sucesso");
        } catch (RuntimeException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }    
        
        new FrameConsultaAeronave().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JLabel jCapacidade;
    private javax.swing.JLabel jCodigo;
    private javax.swing.JLabel jCompanhia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextCapacidade;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextCompanhia;
    private javax.swing.JTextField jTextModelo;
    // End of variables declaration//GEN-END:variables
}
