/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoprog2.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabalhoprog2.controladores.AeroportoController;
import trabalhoprog2.modelos.Aeroporto;

/**
 *
 * @author warml
 */
public class FrameConsultaAeroporto extends javax.swing.JFrame {

    /**
     * Creates new form FrameConsultaAeroporto
     */
    public FrameConsultaAeroporto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAeroportos = new javax.swing.JTable();
        javax.swing.JLabel jAeroportos = new javax.swing.JLabel();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableAeroportos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cidade", "Estado ", "País"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAeroportos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAeroportosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAeroportos);

        jAeroportos.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jAeroportos.setText("Aeroportos");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jAeroportos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAtualizar)
                .addGap(18, 18, 18)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jAeroportos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel modelo = (DefaultTableModel)jTableAeroportos.getModel();
        
        AeroportoController ctc = new AeroportoController();
        List<Aeroporto> aeroportos = ctc.consultarTodos();
        for (Aeroporto aeroporto : aeroportos){
            modelo.addRow(new String[]{
                String.valueOf(aeroporto.getId()),
                        aeroporto.getNome(),
                        aeroporto.getCidade(),
                        aeroporto.getEstado(),
                        aeroporto.getPais()
            });
                
        }
    }//GEN-LAST:event_formWindowOpened

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            AeroportoController ctc = new AeroportoController();
            int linha = jTableAeroportos.getSelectedRow();
            int id = Integer.parseInt(jTableAeroportos.getValueAt(linha, 0).toString());
            ctc.excluir(id);
            
            DefaultTableModel modelo = (DefaultTableModel)jTableAeroportos.getModel();
            modelo.removeRow(linha);
            JOptionPane.showMessageDialog(rootPane, "Aeroporto excluído com sucesso");
            
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(rootPane, "Selecione um aeroporto para excluir");
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTableAeroportosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAeroportosMouseClicked
           
    }//GEN-LAST:event_jTableAeroportosMouseClicked

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        try {   
           int linha = jTableAeroportos.getSelectedRow();
           int id = Integer.parseInt(jTableAeroportos.getValueAt(linha, 0).toString());
           String nome = jTableAeroportos.getValueAt(linha, 1).toString();
           String cidade = jTableAeroportos.getValueAt(linha, 2).toString();
           String estado = jTableAeroportos.getValueAt(linha, 3).toString();
           String pais = jTableAeroportos.getValueAt(linha, 4).toString();
           
           Aeroporto aeroporto = new Aeroporto (nome, cidade, estado, pais, id);
           new FrameAtualizarAeroporto(aeroporto).setVisible(true);
           this.dispose();
        }catch (RuntimeException e){
            JOptionPane.showMessageDialog(rootPane, "Selecione um aeroporto para atualizar");
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAeroportos;
    // End of variables declaration//GEN-END:variables
}
